trussworks/terraform-aws-s3-private-bucket

.circleci/config.yml
.pre-commit-config.yaml
README.md
main.tf
variables.tf

Fixes https://github.com/trussworks/terraform-aws-s3-private-bucket/issues/4 and updates pre-commit and CircleCI.

Enable access logs

---

.circleci/config.yml
.pre-commit-config.yaml
README.md

* Updates the pre-commit hooks and CircleCI primary image to be current
* Adds the pre-commit terraform-docs markers to the README so they are auto-generated

Modernize repository

---

README.md

Update README with instructions on how to run the terratests locally.

Update readme with terratest usage

---

.circleci/config.yml

Update the CircleCI config to run automated terratests for this module.

Add automated terratest to circleci build

---

.circleci/config.yml
.pre-commit-config.yaml
README.md
outputs.tf

It would be nice to have this bucket name so that I don't have to generate the prefix in a different terraform file.

Output bucket name

---

.dependabot/config.yml
.github/workflows/auto-approve.yml

adding dependabot auto merge and github actions auto approve
https://www.pivotaltracker.com/story/show/172659210

adding auto approve and auto merge

---

README.md
examples/simple/main.tf
examples/simple/variables.tf
main.tf
test/terraform_aws_s3_private_bucket_test.go
variables.tf
versions.tf

Another go at this [ticket](https://www.pivotaltracker.com/story/show/169298624). Still need to test in `legendary-waddle-dev`.
I'm not totally sure if this achieves the desired result.

Enable storage class analytics by default

---

main.tf

S3 does not have permissions to put objects in the bucket which is preventing the storage analytics from being exported within the bucket. [Link ](https://docs.aws.amazon.com/en_us/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-9)to where the policy was imported from.
Terraform plan showing the changes of the module and how it impacts a real S3 bucket
<details>
<summary>
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "aws_s3_bucket" "private_bucket" {
acl                         = "private"
arn                         = "arn:aws:s3:::trussworks-ci-lambda-builds-us-west-2"
bucket                      = …
```

Add policy so that s3 can put object in the bucket

---

main.tf

Yes, this means I need to put a new PR in the legendary-waddle-dev too.

Correct analytics prefix

---

.pre-commit-config.yaml
CHANGELOG.md
README.md

[Pivotal story](https://www.pivotaltracker.com/story/show/167742001)
This PR adds a CHANGELOG to this terraform module that has been built using the [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) tool.
Also adds a note about how to do it.

GitHub changelog generator attempt

---

README.md

I merged my last PR and my pre-commit didn't catch that the docs weren't up to spec. Have since fixed this.

Make README pass terradocs specs

---

.github/workflows/auto-approve.yml
go.mod
go.sum

Some more experimentation so I can get this right.

Fix automerge GitHub action

---

.github/workflows/auto-approve.yml
go.mod
go.sum

This is my last attempt to make use of the WyriHaximus/github-action-wait-for-status before giving up and pivoting to something else. 🤞

Fix automerge GitHub action #2

---

.github/workflows/auto-approve.yml
go.mod
go.sum

@ralren - These are the changes I noticed during our investigation.

Copy changes from actions repo for testing

---

.github/workflows/auto-approve.yml
.github/workflows/auto-merge.yml
go.mod
go.sum

Modify the merge github action to trigger when a pull request review has been submitted, check that the state is approved, then try to merge it if suite checks pass successfully.

Automerge if check suite is success

---

.github/workflows/auto-approve.yml
go.mod
go.sum

The auto merge action wasn't triggering because something about the auto approve tool didn't register as a submitted review. I'm forcing the auto approve action to create an approved review instead.

Revert aws-sdk-go and have github-actions submit an approved review

---

.pre-commit-config.yaml
README.md
examples/bucket-inventory/providers.tf
examples/custom-bucket-policy/providers.tf
examples/simple-no-logging/providers.tf
examples/simple/providers.tf
versions.tf

- Adds `providers.tf` files to terratest folders
- Pins the version for the provider in the top-level versions file

Mdawn pin aws providers for terratests 174129036

---

.circleci/config.yml

upgrade circleci-docker-image to circleci

upgrade circleci-docker-image to circleci

---

.github/workflows/tidy.yml
README.md
bin/check-go-version
examples/bucket-inventory/main.tf
examples/bucket-inventory/providers.tf
examples/bucket-inventory/variables.tf
examples/custom-bucket-policy/main.tf
examples/custom-bucket-policy/providers.tf
examples/custom-bucket-policy/variables.tf
examples/simple-no-logging/providers.tf
examples/simple-no-logging/variables.tf
examples/simple/main.tf
examples/simple/providers.tf
examples/simple/variables.tf
go.mod
test/terraform_aws_s3_private_bucket_test.go
test/test_helper.go
versions.tf

- What the title says.
If the apply is successful, Atlantis will delete the branch and plan file.
---
<details><summary>Terraform plan</summary>
```terraform
Add Terraform plan here
```
</details>

Upgrade go version and terraform 13

---

README.md
examples/simple/main.tf
examples/simple/variables.tf
go.mod
go.sum
main.tf
test/terraform_aws_s3_private_bucket_test.go
test/test_helper.go
variables.tf

This appropriates [this suggested change](https://github.com/trussworks/terraform-aws-s3-private-bucket/pull/165) and adds a terratest for our troubles.
Changes proposed:
- adds terratest

add basic test

---

.circleci/config.yml
README.md
bin/check-go-version
examples/simple/main.tf
examples/simple/variables.tf
go.mod
main.tf
test/terraform_aws_s3_private_bucket_test.go
test/test_helper.go
variables.tf

This backports CORS support to 0.12.x.

Backport CORS support to 0.12

---

.circleci/config.yml
.pre-commit-config.yaml
test/terraform_aws_s3_private_bucket_test.go

This enables CI tests for https://github.com/trussworks/terraform-aws-s3-private-bucket/pull/223

update circleci/pre-commit and add a terratest for object expiration

---

.circleci/config.yml
.pre-commit-config.yaml
bin/check-go-version
renovate.json

Disable dependency dashboard, update docker image, update desired Golang value var, and increase timeout for running golangci lint

disable dependency dashboard

---

main.tf
variables.tf

Resolves trussworks/terraform-aws-s3-private-bucket#345

feat: support for S3 Transfer Acceleration

---

.github/workflows/validate.yml

- see [this](https://github.com/trussworks/terraform-aws-s3-private-bucket/actions/runs/4283182731/workflow)

ci: fixing broken action

---

variables.tf

This fixes #407. `use_account_alias_prefix` should be a `bool` not a `string`.

fix: sets proper type on variable
