trussworks/terraform-aws-s3-private-bucket

- README.md
- main.tf
Currently, the module at version 1.5.0 creates a bucket that is "... not public but anyone with appropriate permissions can grant public access to objects." 
i.e. - 
This PR implements terraform's public access block module (https://www.terraform.io/docs/providers/aws/r/s3_bucket_public_access_block.html), so that the bucket is set to "bucket and objects do not have any public access.". This will apply retroactive changes to existing buckets depending on this module, in that the ACL and policies will be set to "private" and disallow future changing to public.
> Update module to disallow public ACL and public policy setting

- main.tf
- variables.tf
There are a variety of times when we don't want the account alias to prefix the bucket name:
* existing project using a different prefix scheme
* using cross-account aliases where the bucket will live in a different account than the user running terraform
This adds an option to disable the account alias prefixing.
The minor version will be bumped when this lands.
> Make account alias prefix optional

- README.md
- outputs.tf
I'd like to be able to access these two variables from the private bucket for use in a cloudfront distribution.
> Output the bucket domain variables

- .circleci/config.yml
- .dependabot/config.yml
- .pre-commit-config.yaml
Addresses: https://www.pivotaltracker.com/story/show/169136125
Add golangci-lint to pre-commit -- https://github.com/golangci/golangci-lint
Add a dependabot config for go modules to be updated weekly.
Have given dependabot access to this repo.
please 👀 and let me know if you want me to name the golint step in the precommit yaml!
> add dependabot for go modules, golangci-lint in precommit

- .circleci/config.yml
- test/terraform_aws_s3_private_bucket_test.go
Per https://www.pivotaltracker.com/story/show/169242580, fix the go module cache path for the terratest CircleCI jobs.
> Update go module cache path for terratest jobs

- test/terraform_aws_s3_private_bucket_test.go
Per https://www.pivotaltracker.com/story/show/169267652, add retry logic to the terratests. We noticed that certain terratests (s3 public access block configuration or bucket encryption) would sporadically fail, but then would succeed when rerunning the test. The errors are most likely due to eventual consistency issues, where the s3 bucket configurations have not fully propagated by the time the terratests are run. This PR attempts to address that issue by leveraging Terratest's retry module.
> Add retries to terratests

- README.md
- versions.tf
It looks like the `IntelligentTieringAccessTier` option for bucket inventory was only added in 2.37.0, so this PR sets a required version on 2.37.0
See https://github.com/terraform-providers/terraform-provider-aws/issues/10743
> require aws provider version be >= 2.37.0

- README.md
- main.tf
- test/terraform_aws_s3_private_bucket_test.go
This PR adds a default bucket policy to deny SSL/TLS on object transmission. This addresses the AWS Config `s3-bucket-ssl-requests-only` requirements.
Note if a user provides a bucket policy they still need to add the deny themselves.
> Setting default bucket policy to enforce TLS

- .circleci/config.yml
- .pre-commit-config.yaml
- Makefile
- bin/check-go-version
- bin/make-test
Just some cleanup for this repo. 😇
-  Adds a `make-test` script which adds terratest metadata to circleci
- Adds a `check-go-version` script 
- Updates makefile, precommit, & circleci to use ^^ both scripts
- Updates circleci to run terratest job instead of validate
> Fix weirdness in golangci hook which forces file duplication within terratest

- Makefile
Fixes a mistake I made in a previous PR by removing the bin in the makefile. See: https://github.com/trussworks/terraform-aws-s3-private-bucket/pull/100#discussion_r429329101
> remove removing the bin

- README.md
- main.tf
- variables.tf
When creating an S3 bucket through terraform, the only way to programmatically remove such bucket is by using the force_destroy argument. The argument is missing form this module, which makes using this module a bit harder when paired with your [terraform-aws-bootstrap](https://github.com/trussworks/terraform-aws-bootstrap) module.
This PR just adds the argument with a safe default of "false".
> Adding variable, default values and force_destroy argument

- main.tf
When you set `use_account_alias_prefix` to `false` this module should not be looking for the account alias via the `data` resource. This edge case comes into play when an account alias has not been set on an AWS account, like during bootstrapping.
I'd like to release this as v2.0.10.
> Disable the data resource that retrieves the AWS account alias if not being used

- .pre-commit-config.yaml
- README.md
- examples/simple/main.tf
- examples/simple/variables.tf
- main.tf
- test/terraform_aws_s3_private_bucket_test.go
- variables.tf
Adds a bool to versioning. 
On MilMove have a bucket for which we would like to remove versioning. If we can remove versioning we won't store unneeded files.  
- Adds bool to versioning, defaulting to true so nothing breaks
- Updates terratest to reflect no breakage
- Updates precommit to appease the Terrform Docs deities
> Adds bool for versioning

- main.tf
The _AWSBucketAnalytics prefix had a preceding / in the name. This appears to be causing issues with the directory structure.
> Fixing _AWSBucketAnalytics prefix name

- README.md
- examples/transitions/main.tf
- examples/transitions/variables.tf
- main.tf
- variables.tf
This change utilizes the `dynamic` blocks in TF13 to allow setting multiple transition blocks on a resource. Here's an example of how this would look:
```hcl
module "s3_bucket" {
source  = "trussworks/s3-private-bucket/aws"
bucket = var.bucket_name
tags   = var.tags
abort_incomplete_multipart_upload_days = 7
transitions = [
{
days          = 30
storage_class = "STANDARD_IA"
},
{
days          = 60
storage_class = "GLACIER"
},
{
days          = 150
storage_class = "DEEP_ARCHIVE"
}
]
noncurrent_version_transitions = [
{
days          = 30
storage_class = "STANDARD_IA"
},
{
days          = 60
storage_class = "GLACIER"
}
]
noncurrent_version_expiration = 90
logging_bucket = module.aws_logs.aws_logs_bucket
}
```
The defaults are all set so that this change should be a no-op for folks using the …
> Enable more control over current and non current object transitions and object expirations lifecycle rules

- .circleci/config.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- versions.tf
This will allow folks on Terraform 0.14 to use this module by setting the minimal supported Terraform version. This is aligned with [Terraforms best practices around versioning](https://www.terraform.io/docs/configuration/version-constraints.html#terraform-core-and-provider-versions). CI tests will also will be using the same version. Lastly, this PR cleans up the CircleCI config and updates pre-commit hooks.  
Once merged, I will remove the `terraform011` branch.
Resolves https://github.com/trussworks/terraform-aws-s3-private-bucket/issues/197
> Relax version constraints for Terraform 0.14 and deprecate Terraform 0.11 support

- .pre-commit-config.yaml
- README.md
- versions.tf
Another quick PR relaxing the AWS provider constraint so that this module can be used in projects using the 3.x AWS provider and Terraform 0.12.
> Relax provider version for 0.12 branch

- README.md
- main.tf
- variables.tf
I would like to supply a customer managed key to this module but it required a change. This should be a no-op for existing users. Folks that wish to update their key can choose to do so. I've tested both configurations of this module.
> Allow users to supply customer managed KMS keys for encryption

- README.md
- main.tf
- variables.tf
I'd like to be able to set the expiration values on the expiration lifecycle policy as mentioned here:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#expiration
I modified the policy to be a no-op for current users of the module and tested it on a local system.
Another way to handle the lifecycle `expiration` policy might be to use dynamic blocks for this to give users more control, but then its possible they might try to use the module without the expiration block. Let me know what you want to do on that and I can update the PR if needed.
> Add expiration variables to control expiration lifecycle policy

- README.md
- examples/object-expiration/main.tf
- examples/object-expiration/variables.tf
- main.tf
- variables.tf
In #220 I didn't realize you couldn't set `date` or `days` and also set `expired_object_delete_marker`. I could change the code to do something fancy with `expiration_days` variable I introduced or I could simplify the logic to work like the other lifecycle policy blocks. I've chosen the latter and set the default to be what it always was, meaning a no-op for users.
From the [TF Docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#expired_object_delete_marker):
> expired_object_delete_marker (Optional) On a versioned bucket (versioning-enabled or versioning-suspended bucket), you can add this element in the lifecycle configuration to direct Amazon S3 to delete expired object delete markers. This cannot be specified with Days or Date in a Lifecycle …
> Use a variable to define expiration blocks similar to transition and noncurrent_version_transition is done.

- README.md
- versions.tf
Lots of breaking changes around s3 resources coming in the [4.0 version of the AWS provider](https://github.com/hashicorp/terraform-provider-aws/issues/20433).  This PR prevents us from falling into those breaking changes until we've made the necessary fixes.
> Restrict to 3.x of the aws provider in anticipation of breaking changes in 4.x

- .circleci/config.yml
- .golangci.yml
- .pre-commit-config.yaml
- README.md
- bin/check-go-version
- examples/bucket-inventory/main.tf
- examples/custom-bucket-policy/main.tf
- examples/simple/main.tf
- examples/simple/variables.tf
- go.mod
- go.sum
- main.tf
- test/terraform_aws_s3_private_bucket_test.go
- variables.tf
- versions.tf
- BREAKING CHANGE: Replaced `enable_versioning` variable (bool) with `versioning_status` (string).
- Migrated all the relevant S3 bucket resources out of `aws_s3_bucket` and into their new respective resources as described in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade
- Set the minimum AWS provider version to 3.75.0, which is the version that contains backported AWS S3 resource functionality that was added in 4.0.
- Updated examples and tests so they reflect the new changes.
- Updated pre-commit hooks, CircleCI image version, Go version, and switched from golint to revive for golanglint-ci.
- Added instructions for how to upgrade once the breaking change is released along with the module version bump.
- Fixed some issues with CI that were …
> Provide an upgrade path to AWS provider 4.0

- main.tf
Looks like recent PR #378 unintentionally also added back the "acl" argument which was ported out from 3.xx to 4.xx upgradation PR (#368) to resource "aws_s3_bucket_acl" . This is giving a warning.
```
│ Warning: Argument is deprecated
│ 
│   with module.terraform_state_bucket.aws_s3_bucket.private_bucket,
│   on .terraform/modules/terraform_state_bucket/main.tf line 79, in resource "aws_s3_bucket" "private_bucket":
│   79:   acl           = "private"
│ 
│ Use the aws_s3_bucket_acl resource instead
│ 
```
> Remove unintentional acl argument to avoid 4.0 deprecation warning

- README.md
- main.tf
- variables.tf
- Adds the variable `additional_lifecycle_rules` which allows a user to specify new rules dynamically
- variable defaults to empty list, so non-breaking change
> [MB-14792] Adds the ability to dynamically create lifecycle rules

- README.md
- main.tf
- variables.tf
- Set bucket encryption configuration based on whether the KMS key id was passed as an argument. If not, default the encryption configuration to AES256.
Fixes #399
> Set sse_algorithm based on presence of kms_master_key_id

- README.md
- main.tf
- variables.tf
Updates the module to account for changes made by AWS in April 2023 to the default security settings of new S3 buckets.
https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/
See the proposed changes in the README `Upgrade Paths` section for more details about the module changes.
If approved, the plan is to release this as a major version update.
> Update the module based on AWS changes to S3 bucket default settings

- main.tf
title, removes these warnings after terraform plan/apply:
```
╷
│ Warning: Deprecated attribute
│
│   on .terraform/modules/lambda_builds_us_gov_west_1/main.tf line 101, in resource "aws_s3_bucket" "private_bucket":
│  101:       policy,
│
│ The attribute "policy" is deprecated. Refer to the provider documentation for
│ details.
│
│ (and 5 more similar warnings elsewhere)
╵
```
> Remove deprecated attributes from s3 bucket ignore_changes block

- .github/workflows/validate.yml
- .gitignore
- .markdownlintrc
- .pre-commit-config.yaml
- .terraform-docs.yml
- README.md
- examples/bucket-inventory/main.tf
- examples/custom-bucket-policy/main.tf
- examples/s3-bucket-key/main.tf
- examples/simple/main.tf
- main.tf
- outputs.tf
- renovate.json
- versions.tf
- **chore: override_policy_document and source_policy_document fixed in this release**
- **chore: renovate renovate config**
- **chore: output the target prefix allowing it to be used in terraform-aws-logs**
- **docs: examples are more accurate**
- **chore: pinning shared action**
- **chore: block tf lock file**
- **chore: pre-commit autoupdate**
- **chore: use valid parameter and get rid of workaround for source_policy_document and override_policy_document**
- **docs: terraform_docs**
[TF Issue 24366](https://github.com/hashicorp/terraform-provider-aws/issues/24366)
[TF Issue 22959](https://github.com/hashicorp/terraform-provider-aws/issues/22959)
> fix: use proper parameters for some s3 bucket resources

- outputs.tf
`aws_s3_logging_bucket.private_bucket` has `count` set which requires an indexed attribute.
> fix: aws_s3_bucket_logging.private_bucket has 'count' set

- README.md
- main.tf
- variables.tf
- versions.tf
- Makes it more clear how to provide a variable to override configuration of aborted, incomplete upload lifecycle rule
- Ensures that rule ^ has all the proper defaults and doesn't throw warnings drift with the provider upgrade
- Allows the analytics and inventory expiration days to be configured by the user as well as to enable/disable those rules if those elements are enabled/disabled rather than always being enabled.
- Made the minimum provider version 5.89 now, and will bump the module version.
> fix: Update module default lifecycle rules to work better with AWS Provider 5.89+

- .pre-commit-config.yaml
- main.tf
- Add empty `filter {}` block to abort-incomplete-multipart-upload lifecycle rule
- Resolve AWS provider warning about missing filter/prefix attributes
- Maintain backward compatibility with existing deployments
```
│ Warning: Invalid Attribute Combination
│ 
│   with module.s3_project.aws_s3_bucket_lifecycle_configuration.private_bucket,
│   on .terraform/modules/s3_document_search/main.tf line 161, in resource "aws_s3_bucket_lifecycle_configuration" "private_bucket":
│  161: resource "aws_s3_bucket_lifecycle_configuration" "private_bucket" {
│ 
│ No attribute specified when one (and only one) of
│ [rule[0].filter,rule[0].prefix] is required
│ 
│ This will be an error in a future version of the provider
```
> fix: add missing filter block to lifecycle configuration
